"""empty message

Revision ID: 5a211a6d2088
Revises: a572d7ed6708
Create Date: 2023-11-12 15:30:08.627221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a211a6d2088'
down_revision = 'a572d7ed6708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection_type')
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connect_type', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'connect_type', ['connect_type'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('connect_type')

    op.create_table('connection_type',
    sa.Column('connect_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['connect_id'], ['connection.id'], name='connection_type_connect_id_fkey'),
    sa.ForeignKeyConstraint(['type_id'], ['connect_type.id'], name='connection_type_type_id_fkey'),
    sa.PrimaryKeyConstraint('connect_id', 'type_id', name='connection_type_pkey')
    )
    # ### end Alembic commands ###
