"""change database

Revision ID: 873798e30658
Revises: d40513a40465
Create Date: 2023-11-12 10:40:50.753499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '873798e30658'
down_revision = 'd40513a40465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('notification', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_payment_added'), ['added'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_payment_datetime'), ['datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_payment_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_payment_updated'), ['updated'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_timestamp')

    op.drop_table('post')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('auth_date', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('added', sa.DateTime(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_user_added'), ['added'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_auth_date'), ['auth_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_photo_url'), ['photo_url'], unique=False)
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_photo_url'))
        batch_op.drop_index(batch_op.f('ix_user_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_first_name'))
        batch_op.drop_index(batch_op.f('ix_user_auth_date'))
        batch_op.drop_index(batch_op.f('ix_user_added'))
        batch_op.create_index('ix_user_email', ['email'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('added')
        batch_op.drop_column('auth_date')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.create_table('post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='post_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_pkey')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('monthly_payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_payment_updated'))
        batch_op.drop_index(batch_op.f('ix_monthly_payment_name'))
        batch_op.drop_index(batch_op.f('ix_monthly_payment_datetime'))
        batch_op.drop_index(batch_op.f('ix_monthly_payment_added'))

    op.drop_table('monthly_payment')
    # ### end Alembic commands ###
