"""empty message

Revision ID: a572d7ed6708
Revises: c2cf8246fbc6
Create Date: 2023-11-12 12:47:02.262473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a572d7ed6708'
down_revision = 'c2cf8246fbc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connect_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connect_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connect_type_name'), ['name'], unique=False)

    op.create_table('connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('connect_link', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connection_connect_link'), ['connect_link'], unique=False)

    op.create_table('connection_type',
    sa.Column('connect_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connect_id'], ['connection.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['connect_type.id'], ),
    sa.PrimaryKeyConstraint('connect_id', 'type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection_type')
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connection_connect_link'))

    op.drop_table('connection')
    with op.batch_alter_table('connect_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connect_type_name'))

    op.drop_table('connect_type')
    # ### end Alembic commands ###
